### ISSUE TITLE
Wrong table added for registration of users

### ISSUE THREAD

**Issue by meghakundu** [HajarAitAbdielmomin/IT-Ticketing-System#1]
The table to be used should be "user" instead of "users". UI for register and login not proper. Login credentials not matching records. Please help with this @HajarAitAbdielmomin

**Comment by HajarAitAbdielmomin** [comment]
The system does not contain a UI for registration. You will need to add a user manually from the database and then try to authenticate to the system using the credentials of the user you registered in the DB.

You just need to follow the instructions mentioned in the README file.

**Comment by meghakundu** [comment]
> The system does not contain a UI for registration. You will need to add a user manually from the database and then try to authenticate to the system using the credentials of the user you registered in the DB.
> 
> You just need to follow the instructions mentioned in the README file.

Though its true, that also shows that "users" table isnot needed. right? @HajarAitAbdielmomin

**Comment by HajarAitAbdielmomin** [comment]
Nope, the 'users' table is generated by Laravel automatically during migration. In my case, I created the 'user' table

**Comment by meghakundu** [comment]
> Nope, the 'users' table is generated by Laravel automatically during migration. In my case, I created the 'user' table

ok :) @HajarAitAbdielmomin
